name: Testing
on:
  schedule:
  - cron: "23 10 * * *"
  workflow_dispatch: 
    inputs:
      number:
        description: "El numero secreto de tu tarjeta de credito"
        required: true
        default: "343948"
      who-to-greet:
        description: "A quien saludar"
        required: true
        default: "pepe"
jobs:
  buenas_a_todos:
    runs-on: ubuntu-latest
    name: A job to say que paxa
    steps:
      - uses: actions/checkout@v3
      - name: A ver si chuta 
        id: buenas
        uses: 'davidgpozo/testing/pruebas/de/concepto@main'
        with:
          who-to-greet: 'Desde el olivar de Badajoz'
      - name: El numero de la loteria
        run: |
          echo random-number ${{ steps.buenas.outputs.random-number }} && date
          echo "Local inputs"
          PA="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m"
          echo ${{ github.event.inputs.number }}
          echo ${{ github.event.inputs.who-to-greet }}
        shell: bash
