name: Testing
on: workflow_dispatch
jobs:
  PushFile:
    runs-on: ubuntu-20.04
    env:
    steps:
    - name: Check out the code
      uses: actions/checkout@v3
    - name: Gen a file
      run: |
        echo "pruebas fichero" > ${{ github.WORKSPACE }}/upFile
    - name: Commit report
      if: ${{ always() }}
      run: |
        git config --global user.name ${{ github.actor }}
        git pull
        git add -f ${{ github.WORKSPACE }}/upFile || true
        git commit -m "Autometed push testing" || true
        git push
