name: Testing
on: workflow_dispatch
jobs:
  PushFile:
    runs-on: ubuntu-20.04
    steps:
    - name: Check out the code
      uses: actions/checkout@v3
    - name: Gen a file
      run: |
        echo "pruebas fichero ${{ github.run_number }}" > ${{ github.WORKSPACE }}/upFile
        pwd
        ls -lah  ${{ github.WORKSPACE }}
    - name: Commit report
      if: ${{ always() }}
      run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
