name: Testing
on:
  schedule:
  - cron: "0 3 * * *"
  workflow_dispatch: *
jobs:
  buenas_a_todos:
    runs-on: ubuntu-latest
    name: A job to say que paxa
    steps:
      - uses: actions/checkout@v3
      - name: A ver si chuta 
        id: buenas
        uses: davidgpozo/testing@v1
        with:
          who-to-greet: 'Desde el olivar de Badajoz'
      - name: El numero de la loteria
        run: echo random-number ${{ steps.buenas.outputs.random-number }}
        shell: bash

